config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :pods, only: %i[index show new create edit update]
  resources :pod_results, only: %i[new create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/league.rb
# frozen_string_literal: true

class League < ApplicationRecord
  has_many :pods, dependent: :destroy
  has_many :users, through: :pods

  validates :year, presence: true
end

app/models/pod.rb
# frozen_string_literal: true

class Pod < ApplicationRecord
  belongs_to :league
  has_many :pod_results, dependent: :destroy
  has_many :users, through: :pod_results

  validates :date, comparison: { less_than_or_equal_to: -> { Time.zone.today } }
  validates :pod_results, length: { minimum: 3 }

  accepts_nested_attributes_for :pod_results
end

app/models/pod_result.rb
# frozen_string_literal: true

class PodResult < ApplicationRecord
  belongs_to :user
  belongs_to :pod

  validates :place, :score, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pod_results, dependent: :destroy
  has_many :pods, through: :pod_results

  validates :first_name, :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    sorted_users = User.joins(:pod_results)
                       .group('users.id')
                       .order('SUM(pod_results.score) DESC')
    service = Users::PrepareStatistics.new(sorted_users)
    service.call

    render :index, locals: { sorted_users:, user_statistics: service.stats }
  end
end

app/controllers/pods_controller.rb
# frozen_string_literal: true

class PodsController < ApplicationController
  def index
    pods = Pod.all

    render :index, locals: { pods: }
  end

  def show
    pod = Pod.find(params[:id])

    render :show, locals: { pod: }
  end

  def new
    pod = Pod.new
    number_of_players = params[:number_of_players].to_i
    number_of_players.times { pod.pod_results.build }

    render :new, locals: { pod: }
  end

  def edit
    pod = Pod.find(params[:id])

    render :edit, locals: { pod: }
  end

  def create
    league = League.find_or_create_by(year: Time.zone.now.year)
    pod = league.pods.new(pod_params)
    Pods::CalculateResults.new(pod).call

    if pod.save
      redirect_to pod, notice: 'Pod was successfully created. Add results'
    else
      render :new, status: :unprocessable_entity, locals: { pod: }
    end
  end

  def update
    pod = Pod.find(params[:id])

    if pod.update(pod_params)
      Pods::CalculateResults.new(pod).call
      pod.save

      redirect_to pod, notice: 'Pod was successfully updated.'
    else
      render :edit, status: :unprocessable_entity, locals: { pod: }
    end
  end

  private

  def pod_params
    params.require(:pod).permit(:date, pod_results_attributes: %i[id user_id place])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.haml
= form_with url: new_pod_path, method: :get do |f|
  .flex.items-center.space-x-4
    = f.label :number_of_players, 'Enter number of players:', class: 'block mb-2 text-sm font-medium text-gray-900 whitespace-nowrap'
    = f.number_field :number_of_players, min: 3, value: 4, required: true, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5'
    = f.submit 'Add New Pod', class: 'text-white bg-gray-700 hover:bg-gray-600 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center'

%h1.text-2xl.font-bold.my-4 Players Statistics
.relative.overflow-x-auto.my-10
  %table.w-full.text-sm.text-left.rtl
    %thead.text-xs.text-gray-700.uppercase.bg-gray-50
      %tr
        %th.px-6.py-3 Player
        %th.px-6.py-3 Total score
        %th.px-6.py-3 Number of wins
        %th.px-6.py-3 Number of games played
        %th.px-6.py-3 Average points per game
        %th.px-6.py-3 Win Rate
        %th.px-6.py-3 Laplace's rule of succession
    %tbody
      - sorted_users.each do |user|
        - stats = user_statistics[user.id]
        %tr.bg-white.border-b
          %td.px-6.py-4= stats[:full_name]
          %td.px-6.py-4= stats[:total_score]
          %td.px-6.py-4= stats[:number_of_wins]
          %td.px-6.py-4= stats[:number_of_played_games]
          %td.px-6.py-4= number_with_precision(stats[:average_points], precision: 2)
          %td.px-6.py-4= number_to_percentage(stats[:win_rate], precision: 2)
          %td.px-6.py-4= number_to_percentage(stats[:laplace_succession], precision: 2)

app/views/layouts/_header.html.erb
<nav class="bg-gray-800" data-controller="menu">
  <div class="container mx-auto px-12">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false" data-action="click->menu#toggle">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
          <%= link_to image_tag('logo.jpeg', class: 'h-8 w-auto', alt: 'Street Magic'), root_path %>
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <%= link_to 'Pods', pods_path, class: 'rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white', aria: { current: 'page' } %>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <% if user_signed_in? %>
          <div class="relative ml-3" data-controller="menu">
              <button type="button" class="flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true" data-action="click->menu#toggle">
                <span class="sr-only">Open user menu</span>
                <%= image_tag 'profile.png', class: 'h-8 w-8 rounded-full', alt: 'Profile' %>
              </button>
              <div class="hidden origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1" data-menu-target="menu">
                <%= link_to 'Edit Profile', edit_user_registration_path, class: 'block px-4 py-2 text-sm text-gray-700', role: 'menuitem', tabindex: '-1' %>
                <%= link_to 'Log Out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'block px-4 py-2 text-sm text-gray-700', role: 'menuitem', tabindex: '-1' %>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>

  <!-- Mobile menu -->
  <div class="hidden" id="mobile-menu" data-menu-target="menu">
    <div class="space-y-1 px-2 pb-3 pt-2">
      <%= link_to 'Pods', pods_path, class: 'rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white', aria: { current: 'page' } %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title StreetMagic
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    = render 'layouts/header'
    %main.container.mx-auto.mt-12.px-12
      %p.notice= notice
      = yield

app/views/pods/_form.html.haml
= form_with model: pod do |form|
  - if pod.errors.any?
    #error_explanation
      %h2
        = pluralize(pod.errors.count, "error") + " prohibited this pod from being saved:"
      %ul
        - pod.errors.full_messages.each do |message|
          %li= message

  = form.label :date
  = form.date_field :date

  - pod.pod_results.each_with_index do |pod_result, index|
    .nested-fields
      = form.fields_for :pod_results, pod_result do |pod_result_fields|
        = pod_result_fields.label :user
        = pod_result_fields.select :user_id, User.all.collect { |u| [u.full_name, u.id] }, include_blank: true
        = pod_result_fields.label :place
        = pod_result_fields.number_field :place

  %p
    = form.submit

app/views/pods/edit.html.haml
= render 'form', pod: pod

app/views/pods/index.html.haml
%h1
  List of all pods:
%ul
  - pods.each do |pod|
    %li= link_to pod.date, pod_path(pod)

app/views/pods/new.html.haml
= render 'form', pod: pod

app/views/pods/show.html.haml
%h1
  Pod information
%h2
  = pod.date
  = link_to 'Edit', edit_pod_path(pod)

%h3
  Pod results
%ul
  - pod.pod_results.each do |pod_result|
    %li
      = pod_result.user.full_name
      %p
        Place:
        = pod_result.place
      %p
        Score:
        = pod_result.score